services:
  app:
    container_name: app
    build: .
    ports:
      - 3000:3000

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ferretdb

  ferret:
    image: ghcr.io/ferretdb/ferretdb:latest
    container_name: ferretdb
    environment:
      FERRETDB_POSTGRESQL_URL: postgres://user:password@postgres:5432/ferretdb
      FERRETDB_TELEMETRY: disable
      FERRETDB_LOG_LEVEL: error
    depends_on:
      - postgres
